services:
  kali-linux-desktop:
    image: iphoneintosh/kali-docker:large
    container_name: kali-desktop
    environment:
      VNCPWD: password123
      VNCPORT: 5900
      NOVNCPORT: 8080
    ports:
      - "9020:8080"
      - "9021:5900"
    networks:
      bridge_net:
        ipv4_address: 172.25.0.2
    tty: true
    stdin_open: true

  tinyproxy-1:
    image: monokal/tinyproxy
    container_name: tinyproxy-1
    ports:
      - "6666:8888"
    command: ANY
    networks:
      bridge_net:
        ipv4_address: 172.25.0.3

  tinyproxy-2:
    image: monokal/tinyproxy
    container_name: tinyproxy-2
    ports:
      - "7777:8888"
    command: ANY
    networks:
      bridge_net:
        ipv4_address: 172.25.0.4

  tinyproxy-3:
    image: monokal/tinyproxy
    container_name: tinyproxy-3
    ports:
      - "8888:8888"
    command: ANY
    networks:
      bridge_net:
        ipv4_address: 172.25.0.5

  ping-pong-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ping-pong-api
    ports:
      - "5000:5000"
    networks:
      bridge_net:
        ipv4_address: 172.25.0.6

networks:
  bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/26
