services:
  kali-linux-desktop:
    image: iphoneintosh/kali-docker:large
    container_name: kali-desktop
    environment:
      VNCPWD: password123
      VNCPORT: 5900
      NOVNCPORT: 8080
    ports:
      - "9020:8080"
      - "9021:5900"
    networks:
      bridge_net:
        ipv4_address: 172.25.0.2
    tty: true
    stdin_open: true

  tinyproxy:
    image: monokal/tinyproxy
    container_name: tinyproxy
    ports:
      - "8888:8888"
    command: ANY
    networks:
      bridge_net:
        ipv4_address: 172.25.0.3

networks:
  bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/26
